# Generated by Django 2.1.2 on 2020-07-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Likes', models.IntegerField(blank=True, default=0, null=True)),
                ('PostedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
